version: '3.8'

services:
  database:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data


  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data

volumes:
  postgres_data_volume: